// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package proto_pharmacy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestCityAndShop struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestCityAndShop) Reset()         { *m = RequestCityAndShop{} }
func (m *RequestCityAndShop) String() string { return proto.CompactTextString(m) }
func (*RequestCityAndShop) ProtoMessage()    {}
func (*RequestCityAndShop) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *RequestCityAndShop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestCityAndShop.Unmarshal(m, b)
}
func (m *RequestCityAndShop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestCityAndShop.Marshal(b, m, deterministic)
}
func (m *RequestCityAndShop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCityAndShop.Merge(m, src)
}
func (m *RequestCityAndShop) XXX_Size() int {
	return xxx_messageInfo_RequestCityAndShop.Size(m)
}
func (m *RequestCityAndShop) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCityAndShop.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCityAndShop proto.InternalMessageInfo

func (m *RequestCityAndShop) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type ResponseCities struct {
	Errors               *ErrorResponse `protobuf:"bytes,1,opt,name=errors,proto3" json:"errors,omitempty"`
	Cities               []*City        `protobuf:"bytes,2,rep,name=cities,proto3" json:"cities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseCities) Reset()         { *m = ResponseCities{} }
func (m *ResponseCities) String() string { return proto.CompactTextString(m) }
func (*ResponseCities) ProtoMessage()    {}
func (*ResponseCities) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *ResponseCities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCities.Unmarshal(m, b)
}
func (m *ResponseCities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCities.Marshal(b, m, deterministic)
}
func (m *ResponseCities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCities.Merge(m, src)
}
func (m *ResponseCities) XXX_Size() int {
	return xxx_messageInfo_ResponseCities.Size(m)
}
func (m *ResponseCities) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCities.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCities proto.InternalMessageInfo

func (m *ResponseCities) GetErrors() *ErrorResponse {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseCities) GetCities() []*City {
	if m != nil {
		return m.Cities
	}
	return nil
}

type ResponseShops struct {
	Errors               *ErrorResponse `protobuf:"bytes,1,opt,name=errors,proto3" json:"errors,omitempty"`
	Shops                []*Shop        `protobuf:"bytes,2,rep,name=shops,proto3" json:"shops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseShops) Reset()         { *m = ResponseShops{} }
func (m *ResponseShops) String() string { return proto.CompactTextString(m) }
func (*ResponseShops) ProtoMessage()    {}
func (*ResponseShops) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *ResponseShops) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseShops.Unmarshal(m, b)
}
func (m *ResponseShops) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseShops.Marshal(b, m, deterministic)
}
func (m *ResponseShops) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseShops.Merge(m, src)
}
func (m *ResponseShops) XXX_Size() int {
	return xxx_messageInfo_ResponseShops.Size(m)
}
func (m *ResponseShops) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseShops.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseShops proto.InternalMessageInfo

func (m *ResponseShops) GetErrors() *ErrorResponse {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseShops) GetShops() []*Shop {
	if m != nil {
		return m.Shops
	}
	return nil
}

type ErrorResponse struct {
	IsError              bool     `protobuf:"varint,1,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *ErrorResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Запрос на получение сопоставленных по коду Puls ----|
type RequestOnOneCodePuls struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	LastId               int64    `protobuf:"varint,3,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	DateUpdatedLte       string   `protobuf:"bytes,4,opt,name=date_updated_lte,json=dateUpdatedLte,proto3" json:"date_updated_lte,omitempty"`
	DateUpdatedGte       string   `protobuf:"bytes,5,opt,name=date_updated_gte,json=dateUpdatedGte,proto3" json:"date_updated_gte,omitempty"`
	PulsCode             string   `protobuf:"bytes,6,opt,name=puls_code,json=pulsCode,proto3" json:"puls_code,omitempty"`
	CityId               int64    `protobuf:"varint,7,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestOnOneCodePuls) Reset()         { *m = RequestOnOneCodePuls{} }
func (m *RequestOnOneCodePuls) String() string { return proto.CompactTextString(m) }
func (*RequestOnOneCodePuls) ProtoMessage()    {}
func (*RequestOnOneCodePuls) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *RequestOnOneCodePuls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestOnOneCodePuls.Unmarshal(m, b)
}
func (m *RequestOnOneCodePuls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestOnOneCodePuls.Marshal(b, m, deterministic)
}
func (m *RequestOnOneCodePuls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestOnOneCodePuls.Merge(m, src)
}
func (m *RequestOnOneCodePuls) XXX_Size() int {
	return xxx_messageInfo_RequestOnOneCodePuls.Size(m)
}
func (m *RequestOnOneCodePuls) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestOnOneCodePuls.DiscardUnknown(m)
}

var xxx_messageInfo_RequestOnOneCodePuls proto.InternalMessageInfo

func (m *RequestOnOneCodePuls) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *RequestOnOneCodePuls) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RequestOnOneCodePuls) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *RequestOnOneCodePuls) GetDateUpdatedLte() string {
	if m != nil {
		return m.DateUpdatedLte
	}
	return ""
}

func (m *RequestOnOneCodePuls) GetDateUpdatedGte() string {
	if m != nil {
		return m.DateUpdatedGte
	}
	return ""
}

func (m *RequestOnOneCodePuls) GetPulsCode() string {
	if m != nil {
		return m.PulsCode
	}
	return ""
}

func (m *RequestOnOneCodePuls) GetCityId() int64 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type ResponseOnOneCodePuls struct {
	Errors               *ErrorResponse `protobuf:"bytes,1,opt,name=errors,proto3" json:"errors,omitempty"`
	LastId               int64          `protobuf:"varint,2,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Limit                int64          `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	DateUpdatedLte       string         `protobuf:"bytes,4,opt,name=date_updated_lte,json=dateUpdatedLte,proto3" json:"date_updated_lte,omitempty"`
	DateUpdatedGte       string         `protobuf:"bytes,5,opt,name=date_updated_gte,json=dateUpdatedGte,proto3" json:"date_updated_gte,omitempty"`
	Goods                []*Product     `protobuf:"bytes,6,rep,name=goods,proto3" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseOnOneCodePuls) Reset()         { *m = ResponseOnOneCodePuls{} }
func (m *ResponseOnOneCodePuls) String() string { return proto.CompactTextString(m) }
func (*ResponseOnOneCodePuls) ProtoMessage()    {}
func (*ResponseOnOneCodePuls) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}

func (m *ResponseOnOneCodePuls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseOnOneCodePuls.Unmarshal(m, b)
}
func (m *ResponseOnOneCodePuls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseOnOneCodePuls.Marshal(b, m, deterministic)
}
func (m *ResponseOnOneCodePuls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseOnOneCodePuls.Merge(m, src)
}
func (m *ResponseOnOneCodePuls) XXX_Size() int {
	return xxx_messageInfo_ResponseOnOneCodePuls.Size(m)
}
func (m *ResponseOnOneCodePuls) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseOnOneCodePuls.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseOnOneCodePuls proto.InternalMessageInfo

func (m *ResponseOnOneCodePuls) GetErrors() *ErrorResponse {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseOnOneCodePuls) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *ResponseOnOneCodePuls) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ResponseOnOneCodePuls) GetDateUpdatedLte() string {
	if m != nil {
		return m.DateUpdatedLte
	}
	return ""
}

func (m *ResponseOnOneCodePuls) GetDateUpdatedGte() string {
	if m != nil {
		return m.DateUpdatedGte
	}
	return ""
}

func (m *ResponseOnOneCodePuls) GetGoods() []*Product {
	if m != nil {
		return m.Goods
	}
	return nil
}

// Запрос для получения всех данных (limit/last_id) ---|
type RequestAllProducts struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	LastId               int64    `protobuf:"varint,3,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	DateUpdatedLte       string   `protobuf:"bytes,4,opt,name=date_updated_lte,json=dateUpdatedLte,proto3" json:"date_updated_lte,omitempty"`
	DateUpdatedGte       string   `protobuf:"bytes,5,opt,name=date_updated_gte,json=dateUpdatedGte,proto3" json:"date_updated_gte,omitempty"`
	CityId               int64    `protobuf:"varint,6,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAllProducts) Reset()         { *m = RequestAllProducts{} }
func (m *RequestAllProducts) String() string { return proto.CompactTextString(m) }
func (*RequestAllProducts) ProtoMessage()    {}
func (*RequestAllProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{6}
}

func (m *RequestAllProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAllProducts.Unmarshal(m, b)
}
func (m *RequestAllProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAllProducts.Marshal(b, m, deterministic)
}
func (m *RequestAllProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAllProducts.Merge(m, src)
}
func (m *RequestAllProducts) XXX_Size() int {
	return xxx_messageInfo_RequestAllProducts.Size(m)
}
func (m *RequestAllProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAllProducts.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAllProducts proto.InternalMessageInfo

func (m *RequestAllProducts) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *RequestAllProducts) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RequestAllProducts) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *RequestAllProducts) GetDateUpdatedLte() string {
	if m != nil {
		return m.DateUpdatedLte
	}
	return ""
}

func (m *RequestAllProducts) GetDateUpdatedGte() string {
	if m != nil {
		return m.DateUpdatedGte
	}
	return ""
}

func (m *RequestAllProducts) GetCityId() int64 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type ResponseAllProducts struct {
	Errors               *ErrorResponse `protobuf:"bytes,1,opt,name=errors,proto3" json:"errors,omitempty"`
	LastId               int64          `protobuf:"varint,2,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Limit                int64          `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	DateUpdatedLte       string         `protobuf:"bytes,4,opt,name=date_updated_lte,json=dateUpdatedLte,proto3" json:"date_updated_lte,omitempty"`
	DateUpdatedGte       string         `protobuf:"bytes,5,opt,name=date_updated_gte,json=dateUpdatedGte,proto3" json:"date_updated_gte,omitempty"`
	Goods                []*Puls        `protobuf:"bytes,6,rep,name=goods,proto3" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseAllProducts) Reset()         { *m = ResponseAllProducts{} }
func (m *ResponseAllProducts) String() string { return proto.CompactTextString(m) }
func (*ResponseAllProducts) ProtoMessage()    {}
func (*ResponseAllProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{7}
}

func (m *ResponseAllProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAllProducts.Unmarshal(m, b)
}
func (m *ResponseAllProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAllProducts.Marshal(b, m, deterministic)
}
func (m *ResponseAllProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAllProducts.Merge(m, src)
}
func (m *ResponseAllProducts) XXX_Size() int {
	return xxx_messageInfo_ResponseAllProducts.Size(m)
}
func (m *ResponseAllProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAllProducts.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAllProducts proto.InternalMessageInfo

func (m *ResponseAllProducts) GetErrors() *ErrorResponse {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseAllProducts) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *ResponseAllProducts) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ResponseAllProducts) GetDateUpdatedLte() string {
	if m != nil {
		return m.DateUpdatedLte
	}
	return ""
}

func (m *ResponseAllProducts) GetDateUpdatedGte() string {
	if m != nil {
		return m.DateUpdatedGte
	}
	return ""
}

func (m *ResponseAllProducts) GetGoods() []*Puls {
	if m != nil {
		return m.Goods
	}
	return nil
}

// Запрос с списком sku конкурента ------|
type RequestOnCompetitorSku struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CompetitorName       string   `protobuf:"bytes,2,opt,name=competitor_name,json=competitorName,proto3" json:"competitor_name,omitempty"`
	Codes                []string `protobuf:"bytes,3,rep,name=codes,proto3" json:"codes,omitempty"`
	DateUpdatedLte       string   `protobuf:"bytes,4,opt,name=date_updated_lte,json=dateUpdatedLte,proto3" json:"date_updated_lte,omitempty"`
	DateUpdatedGte       string   `protobuf:"bytes,5,opt,name=date_updated_gte,json=dateUpdatedGte,proto3" json:"date_updated_gte,omitempty"`
	LastId               int64    `protobuf:"varint,6,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Limit                int64    `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestOnCompetitorSku) Reset()         { *m = RequestOnCompetitorSku{} }
func (m *RequestOnCompetitorSku) String() string { return proto.CompactTextString(m) }
func (*RequestOnCompetitorSku) ProtoMessage()    {}
func (*RequestOnCompetitorSku) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{8}
}

func (m *RequestOnCompetitorSku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestOnCompetitorSku.Unmarshal(m, b)
}
func (m *RequestOnCompetitorSku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestOnCompetitorSku.Marshal(b, m, deterministic)
}
func (m *RequestOnCompetitorSku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestOnCompetitorSku.Merge(m, src)
}
func (m *RequestOnCompetitorSku) XXX_Size() int {
	return xxx_messageInfo_RequestOnCompetitorSku.Size(m)
}
func (m *RequestOnCompetitorSku) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestOnCompetitorSku.DiscardUnknown(m)
}

var xxx_messageInfo_RequestOnCompetitorSku proto.InternalMessageInfo

func (m *RequestOnCompetitorSku) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *RequestOnCompetitorSku) GetCompetitorName() string {
	if m != nil {
		return m.CompetitorName
	}
	return ""
}

func (m *RequestOnCompetitorSku) GetCodes() []string {
	if m != nil {
		return m.Codes
	}
	return nil
}

func (m *RequestOnCompetitorSku) GetDateUpdatedLte() string {
	if m != nil {
		return m.DateUpdatedLte
	}
	return ""
}

func (m *RequestOnCompetitorSku) GetDateUpdatedGte() string {
	if m != nil {
		return m.DateUpdatedGte
	}
	return ""
}

func (m *RequestOnCompetitorSku) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *RequestOnCompetitorSku) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ResponseOnCompetitorSku struct {
	Errors               *ErrorResponse `protobuf:"bytes,1,opt,name=errors,proto3" json:"errors,omitempty"`
	Goods                []*Product     `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseOnCompetitorSku) Reset()         { *m = ResponseOnCompetitorSku{} }
func (m *ResponseOnCompetitorSku) String() string { return proto.CompactTextString(m) }
func (*ResponseOnCompetitorSku) ProtoMessage()    {}
func (*ResponseOnCompetitorSku) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{9}
}

func (m *ResponseOnCompetitorSku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseOnCompetitorSku.Unmarshal(m, b)
}
func (m *ResponseOnCompetitorSku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseOnCompetitorSku.Marshal(b, m, deterministic)
}
func (m *ResponseOnCompetitorSku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseOnCompetitorSku.Merge(m, src)
}
func (m *ResponseOnCompetitorSku) XXX_Size() int {
	return xxx_messageInfo_ResponseOnCompetitorSku.Size(m)
}
func (m *ResponseOnCompetitorSku) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseOnCompetitorSku.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseOnCompetitorSku proto.InternalMessageInfo

func (m *ResponseOnCompetitorSku) GetErrors() *ErrorResponse {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ResponseOnCompetitorSku) GetGoods() []*Product {
	if m != nil {
		return m.Goods
	}
	return nil
}

// Модели данных -------------------------|
type Puls struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PulsCode             string     `protobuf:"bytes,2,opt,name=puls_code,json=pulsCode,proto3" json:"puls_code,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Manufacturer         string     `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	CompetitorGoods      []*Product `protobuf:"bytes,5,rep,name=competitor_goods,json=competitorGoods,proto3" json:"competitor_goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Puls) Reset()         { *m = Puls{} }
func (m *Puls) String() string { return proto.CompactTextString(m) }
func (*Puls) ProtoMessage()    {}
func (*Puls) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{10}
}

func (m *Puls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Puls.Unmarshal(m, b)
}
func (m *Puls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Puls.Marshal(b, m, deterministic)
}
func (m *Puls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Puls.Merge(m, src)
}
func (m *Puls) XXX_Size() int {
	return xxx_messageInfo_Puls.Size(m)
}
func (m *Puls) XXX_DiscardUnknown() {
	xxx_messageInfo_Puls.DiscardUnknown(m)
}

var xxx_messageInfo_Puls proto.InternalMessageInfo

func (m *Puls) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Puls) GetPulsCode() string {
	if m != nil {
		return m.PulsCode
	}
	return ""
}

func (m *Puls) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Puls) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Puls) GetCompetitorGoods() []*Product {
	if m != nil {
		return m.CompetitorGoods
	}
	return nil
}

type Product struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku                  string   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Article              string   `protobuf:"bytes,3,opt,name=article,proto3" json:"article,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price                int64    `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	PriceOld             int64    `protobuf:"varint,6,opt,name=price_old,json=priceOld,proto3" json:"price_old,omitempty"`
	IsActive             bool     `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Brand                string   `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Manufacturer         string   `protobuf:"bytes,9,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Country              string   `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	Url                  string   `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Category             string   `protobuf:"bytes,12,opt,name=category,proto3" json:"category,omitempty"`
	DateUpdated          string   `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated,proto3" json:"date_updated,omitempty"`
	ShopName             string   `protobuf:"bytes,14,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	City                 *City    `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	Shop                 *Shop    `protobuf:"bytes,16,opt,name=shop,proto3" json:"shop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{11}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Product) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetPriceOld() int64 {
	if m != nil {
		return m.PriceOld
	}
	return 0
}

func (m *Product) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Product) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Product) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Product) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Product) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetDateUpdated() string {
	if m != nil {
		return m.DateUpdated
	}
	return ""
}

func (m *Product) GetShopName() string {
	if m != nil {
		return m.ShopName
	}
	return ""
}

func (m *Product) GetCity() *City {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *Product) GetShop() *Shop {
	if m != nil {
		return m.Shop
	}
	return nil
}

type City struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{12}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *City) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Shop struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{13}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestCityAndShop)(nil), "proto_pharmacy.RequestCityAndShop")
	proto.RegisterType((*ResponseCities)(nil), "proto_pharmacy.ResponseCities")
	proto.RegisterType((*ResponseShops)(nil), "proto_pharmacy.ResponseShops")
	proto.RegisterType((*ErrorResponse)(nil), "proto_pharmacy.ErrorResponse")
	proto.RegisterType((*RequestOnOneCodePuls)(nil), "proto_pharmacy.RequestOnOneCodePuls")
	proto.RegisterType((*ResponseOnOneCodePuls)(nil), "proto_pharmacy.ResponseOnOneCodePuls")
	proto.RegisterType((*RequestAllProducts)(nil), "proto_pharmacy.RequestAllProducts")
	proto.RegisterType((*ResponseAllProducts)(nil), "proto_pharmacy.ResponseAllProducts")
	proto.RegisterType((*RequestOnCompetitorSku)(nil), "proto_pharmacy.RequestOnCompetitorSku")
	proto.RegisterType((*ResponseOnCompetitorSku)(nil), "proto_pharmacy.ResponseOnCompetitorSku")
	proto.RegisterType((*Puls)(nil), "proto_pharmacy.Puls")
	proto.RegisterType((*Product)(nil), "proto_pharmacy.Product")
	proto.RegisterType((*City)(nil), "proto_pharmacy.City")
	proto.RegisterType((*Shop)(nil), "proto_pharmacy.Shop")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 891 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x4f, 0xec, 0xc4, 0x71, 0x5e, 0xdb, 0x6c, 0x34, 0x74, 0xe9, 0x10, 0xb4, 0xa8, 0x98, 0x3f,
	0x1b, 0x55, 0x6c, 0x0f, 0x45, 0xdc, 0xb8, 0x94, 0x0a, 0x45, 0x15, 0x88, 0x16, 0xaf, 0x38, 0x71,
	0xb0, 0xbc, 0xf6, 0x6c, 0x77, 0x54, 0xc7, 0x36, 0x33, 0x63, 0xa4, 0x9c, 0xe0, 0x1b, 0xf1, 0x11,
	0x38, 0xf3, 0x1d, 0xf8, 0x00, 0xdc, 0x39, 0x72, 0x41, 0xf3, 0xc6, 0x4e, 0xc7, 0x49, 0x8c, 0xaa,
	0x4a, 0x95, 0xd8, 0x93, 0xfd, 0xde, 0xfc, 0xe6, 0xcd, 0x7b, 0xbf, 0xdf, 0xbc, 0x99, 0x81, 0x83,
	0x52, 0x14, 0x69, 0x95, 0xa8, 0xd3, 0x52, 0x14, 0xaa, 0x20, 0x13, 0xfc, 0x44, 0xe5, 0x9b, 0x58,
	0x2c, 0xe3, 0x64, 0x15, 0xbc, 0x00, 0x12, 0xb2, 0x9f, 0x2a, 0x26, 0xd5, 0x05, 0x57, 0xab, 0xf3,
	0x3c, 0x7d, 0xf9, 0xa6, 0x28, 0xc9, 0x11, 0x8c, 0xe2, 0x92, 0x47, 0xb7, 0x6c, 0x45, 0xfb, 0xc7,
	0xfd, 0xf9, 0x38, 0xf4, 0xe2, 0x92, 0x7f, 0xc3, 0x56, 0x41, 0x05, 0x93, 0x90, 0xc9, 0xb2, 0xc8,
	0x25, 0xbb, 0xe0, 0x8a, 0x33, 0x49, 0xbe, 0x00, 0x8f, 0x09, 0x51, 0x08, 0x89, 0xc8, 0xbd, 0xb3,
	0x67, 0xa7, 0xed, 0x15, 0x4e, 0xbf, 0xd6, 0xa3, 0xcd, 0xa4, 0xb0, 0x06, 0x93, 0xcf, 0xc0, 0x4b,
	0x30, 0x00, 0x75, 0x8e, 0xdd, 0xf9, 0xde, 0xd9, 0xe1, 0xe6, 0x34, 0x9d, 0x4e, 0x58, 0x63, 0x02,
	0x01, 0x07, 0x4d, 0x04, 0x9d, 0xdf, 0x83, 0x57, 0x3d, 0x81, 0xa1, 0xd4, 0xf3, 0xbb, 0x16, 0xd5,
	0xc1, 0x43, 0x03, 0x09, 0xbe, 0x84, 0x83, 0x56, 0x10, 0xf2, 0x1e, 0xf8, 0x5c, 0x46, 0x18, 0x09,
	0x57, 0xf5, 0xc3, 0x11, 0x97, 0x08, 0x21, 0x53, 0x70, 0x97, 0xf2, 0x86, 0x3a, 0xc8, 0x95, 0xfe,
	0x0d, 0xfe, 0xea, 0xc3, 0x61, 0x4d, 0xec, 0x55, 0x7e, 0x95, 0xb3, 0x8b, 0x22, 0x65, 0xd7, 0x55,
	0x26, 0x3b, 0xa9, 0x25, 0x87, 0x30, 0xcc, 0xf8, 0x92, 0x2b, 0x8c, 0xe2, 0x86, 0xc6, 0xd0, 0xf0,
	0x2c, 0x96, 0x2a, 0xe2, 0x29, 0x75, 0xd1, 0xef, 0x69, 0xf3, 0x32, 0x25, 0x73, 0x98, 0xa6, 0xb1,
	0x62, 0x51, 0x55, 0xea, 0x4f, 0x1a, 0x65, 0x8a, 0xd1, 0x01, 0x06, 0x9c, 0x68, 0xc7, 0x0f, 0xc6,
	0xfd, 0xad, 0x62, 0x5b, 0xc8, 0x1b, 0xc5, 0xe8, 0x70, 0x0b, 0xb9, 0x50, 0x8c, 0xbc, 0x0f, 0xe3,
	0xb2, 0xca, 0x64, 0x94, 0x14, 0x29, 0xa3, 0x1e, 0x42, 0x7c, 0xed, 0xd0, 0xc9, 0xeb, 0x4c, 0x12,
	0xae, 0x56, 0x3a, 0x93, 0x91, 0xc9, 0x44, 0x9b, 0x97, 0x69, 0xf0, 0xab, 0x03, 0x4f, 0x1b, 0x92,
	0xda, 0xb5, 0x3e, 0x50, 0x25, 0xab, 0x66, 0xa7, 0x55, 0xf3, 0x9a, 0x22, 0xd7, 0xa6, 0xe8, 0x31,
	0x98, 0x78, 0x01, 0xc3, 0x9b, 0xa2, 0x48, 0x25, 0xf5, 0x70, 0xa3, 0x1c, 0x6d, 0x26, 0x7e, 0x6d,
	0x9a, 0x2a, 0x34, 0xa8, 0xe0, 0x8f, 0xfe, 0xba, 0x8d, 0xce, 0xb3, 0xac, 0x1e, 0xfc, 0x7f, 0x6b,
	0x6d, 0xc9, 0xe9, 0xb5, 0xe4, 0xfc, 0xa7, 0x0f, 0xef, 0x34, 0x92, 0xd8, 0xc5, 0xbc, 0xbd, 0x62,
	0x9e, 0xb4, 0xc5, 0xdc, 0xea, 0x7a, 0xbd, 0x57, 0x1b, 0x25, 0xff, 0xee, 0xc3, 0xbb, 0xeb, 0xbe,
	0xbd, 0x28, 0x96, 0x25, 0x53, 0x5c, 0x15, 0xe2, 0xe5, 0x6d, 0xd5, 0xad, 0xe6, 0x73, 0x78, 0x92,
	0xac, 0x91, 0x51, 0x1e, 0x2f, 0x59, 0x7d, 0x12, 0x4c, 0xee, 0xdc, 0xdf, 0xc5, 0x4b, 0xa6, 0x4b,
	0xd6, 0xad, 0x25, 0xa9, 0x7b, 0xec, 0xce, 0xc7, 0xa1, 0x31, 0x1e, 0x4b, 0xdd, 0x86, 0x75, 0x6f,
	0x37, 0xeb, 0x23, 0x8b, 0xf5, 0xe0, 0x17, 0x38, 0xba, 0xeb, 0xe0, 0x76, 0xd5, 0x0f, 0x94, 0x7d,
	0xdd, 0x40, 0xce, 0xbd, 0x1a, 0xe8, 0xb7, 0x3e, 0x0c, 0xf0, 0xc8, 0x98, 0x80, 0xc3, 0x53, 0x5c,
	0xca, 0x0d, 0x1d, 0x9e, 0xb6, 0x8f, 0x24, 0x67, 0xe3, 0x48, 0x22, 0x30, 0x40, 0xb6, 0x5d, 0xf4,
	0xe3, 0x3f, 0x09, 0x60, 0x7f, 0x19, 0xe7, 0xd5, 0xeb, 0x38, 0x51, 0x95, 0x60, 0xa2, 0x66, 0xb2,
	0xe5, 0x23, 0x5f, 0xc1, 0xd4, 0x12, 0xcc, 0xe4, 0x39, 0xfc, 0xef, 0x3c, 0x2d, 0x85, 0x17, 0x98,
	0xf1, 0xef, 0x2e, 0x8c, 0xea, 0xc1, 0xad, 0xa4, 0xa7, 0xe0, 0xca, 0xdb, 0xaa, 0xb9, 0x0e, 0xe4,
	0x6d, 0x45, 0x28, 0x8c, 0x62, 0xa1, 0x78, 0x92, 0x35, 0xc9, 0x36, 0xe6, 0xba, 0x86, 0x81, 0x55,
	0xc3, 0x21, 0x0c, 0x4b, 0xc1, 0x13, 0x23, 0xae, 0x1b, 0x1a, 0x03, 0xa9, 0xd0, 0x3f, 0x51, 0x91,
	0x35, 0xaa, 0xfa, 0xe8, 0xb8, 0xca, 0x90, 0x27, 0x2e, 0xa3, 0x38, 0x51, 0xfc, 0x67, 0x86, 0xda,
	0xfa, 0xa1, 0xcf, 0xe5, 0x39, 0xda, 0x3a, 0xde, 0x2b, 0x11, 0xe7, 0x29, 0xf5, 0x71, 0x11, 0x63,
	0x6c, 0x31, 0x35, 0xde, 0xc1, 0x14, 0x85, 0x51, 0x52, 0x54, 0xb9, 0x12, 0x2b, 0x0a, 0x26, 0xef,
	0xda, 0xd4, 0x35, 0x56, 0x22, 0xa3, 0x7b, 0xa6, 0xc6, 0x4a, 0x64, 0x64, 0x06, 0x7e, 0x12, 0x2b,
	0x76, 0x53, 0x88, 0x15, 0xdd, 0x37, 0x4a, 0x35, 0x36, 0xf9, 0x10, 0xf6, 0xed, 0x9d, 0x4b, 0x0f,
	0x70, 0x7c, 0xcf, 0xda, 0xb5, 0xba, 0x02, 0x7d, 0xf1, 0x9a, 0xfe, 0x99, 0x98, 0xf9, 0xda, 0x81,
	0x9d, 0x33, 0x87, 0x81, 0x3e, 0x9e, 0xe8, 0x13, 0xdc, 0x83, 0xbb, 0x1f, 0x0b, 0x88, 0xd0, 0x48,
	0x3d, 0x8b, 0x4e, 0x77, 0x23, 0xf1, 0x86, 0x47, 0x44, 0x70, 0x02, 0x03, 0x3d, 0x6f, 0x4b, 0xbd,
	0x46, 0x11, 0xe7, 0x4e, 0x11, 0x8d, 0xc5, 0x87, 0xd1, 0x3d, 0xb0, 0x67, 0x7f, 0xba, 0xe0, 0x9e,
	0x5f, 0x5f, 0x92, 0x0c, 0x8e, 0x16, 0x4c, 0xe1, 0x6e, 0xd9, 0x6c, 0xaa, 0x4f, 0x37, 0xd3, 0xda,
	0x7d, 0xe4, 0xcc, 0x9e, 0x6f, 0xe3, 0x76, 0x76, 0x69, 0xd0, 0x23, 0x3f, 0xc2, 0x64, 0xc1, 0x5a,
	0xb7, 0x4f, 0xd0, 0xb1, 0x88, 0x85, 0x99, 0x7d, 0xd4, 0xb5, 0x80, 0x05, 0x0a, 0x7a, 0xe4, 0x35,
	0x3c, 0xbd, 0x2b, 0xc5, 0xbe, 0xe1, 0x3f, 0xee, 0x2c, 0xc4, 0x42, 0xcd, 0x3e, 0xe9, 0x2e, 0xc3,
	0x82, 0x05, 0x3d, 0xf2, 0x3d, 0x8c, 0x17, 0x4c, 0xd5, 0x2f, 0xcb, 0xae, 0xfc, 0xad, 0x87, 0xea,
	0xec, 0x83, 0xae, 0xc8, 0x26, 0x46, 0xd0, 0x23, 0x57, 0xe0, 0x2f, 0x98, 0x32, 0xaf, 0xc6, 0xfb,
	0x44, 0x7c, 0xd6, 0x15, 0x11, 0x43, 0x04, 0xbd, 0x57, 0x1e, 0x8e, 0x7f, 0xfe, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xdb, 0x0d, 0xef, 0x85, 0x59, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	GetGoodsOnCompetitorSku(ctx context.Context, in *RequestOnCompetitorSku, opts ...grpc.CallOption) (*ResponseOnCompetitorSku, error)
	GetAllProducts(ctx context.Context, in *RequestAllProducts, opts ...grpc.CallOption) (*ResponseAllProducts, error)
	GetGoodsOnOneCodePuls(ctx context.Context, in *RequestOnOneCodePuls, opts ...grpc.CallOption) (*ResponseOnOneCodePuls, error)
	GetCities(ctx context.Context, in *RequestCityAndShop, opts ...grpc.CallOption) (*ResponseCities, error)
	GetShops(ctx context.Context, in *RequestCityAndShop, opts ...grpc.CallOption) (*ResponseShops, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetGoodsOnCompetitorSku(ctx context.Context, in *RequestOnCompetitorSku, opts ...grpc.CallOption) (*ResponseOnCompetitorSku, error) {
	out := new(ResponseOnCompetitorSku)
	err := c.cc.Invoke(ctx, "/proto_pharmacy.API/GetGoodsOnCompetitorSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetAllProducts(ctx context.Context, in *RequestAllProducts, opts ...grpc.CallOption) (*ResponseAllProducts, error) {
	out := new(ResponseAllProducts)
	err := c.cc.Invoke(ctx, "/proto_pharmacy.API/GetAllProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetGoodsOnOneCodePuls(ctx context.Context, in *RequestOnOneCodePuls, opts ...grpc.CallOption) (*ResponseOnOneCodePuls, error) {
	out := new(ResponseOnOneCodePuls)
	err := c.cc.Invoke(ctx, "/proto_pharmacy.API/GetGoodsOnOneCodePuls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetCities(ctx context.Context, in *RequestCityAndShop, opts ...grpc.CallOption) (*ResponseCities, error) {
	out := new(ResponseCities)
	err := c.cc.Invoke(ctx, "/proto_pharmacy.API/GetCities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetShops(ctx context.Context, in *RequestCityAndShop, opts ...grpc.CallOption) (*ResponseShops, error) {
	out := new(ResponseShops)
	err := c.cc.Invoke(ctx, "/proto_pharmacy.API/GetShops", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	GetGoodsOnCompetitorSku(context.Context, *RequestOnCompetitorSku) (*ResponseOnCompetitorSku, error)
	GetAllProducts(context.Context, *RequestAllProducts) (*ResponseAllProducts, error)
	GetGoodsOnOneCodePuls(context.Context, *RequestOnOneCodePuls) (*ResponseOnOneCodePuls, error)
	GetCities(context.Context, *RequestCityAndShop) (*ResponseCities, error)
	GetShops(context.Context, *RequestCityAndShop) (*ResponseShops, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) GetGoodsOnCompetitorSku(ctx context.Context, req *RequestOnCompetitorSku) (*ResponseOnCompetitorSku, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsOnCompetitorSku not implemented")
}
func (*UnimplementedAPIServer) GetAllProducts(ctx context.Context, req *RequestAllProducts) (*ResponseAllProducts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProducts not implemented")
}
func (*UnimplementedAPIServer) GetGoodsOnOneCodePuls(ctx context.Context, req *RequestOnOneCodePuls) (*ResponseOnOneCodePuls, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsOnOneCodePuls not implemented")
}
func (*UnimplementedAPIServer) GetCities(ctx context.Context, req *RequestCityAndShop) (*ResponseCities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCities not implemented")
}
func (*UnimplementedAPIServer) GetShops(ctx context.Context, req *RequestCityAndShop) (*ResponseShops, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShops not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetGoodsOnCompetitorSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestOnCompetitorSku)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetGoodsOnCompetitorSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_pharmacy.API/GetGoodsOnCompetitorSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetGoodsOnCompetitorSku(ctx, req.(*RequestOnCompetitorSku))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetAllProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAllProducts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAllProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_pharmacy.API/GetAllProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAllProducts(ctx, req.(*RequestAllProducts))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetGoodsOnOneCodePuls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestOnOneCodePuls)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetGoodsOnOneCodePuls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_pharmacy.API/GetGoodsOnOneCodePuls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetGoodsOnOneCodePuls(ctx, req.(*RequestOnOneCodePuls))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCityAndShop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_pharmacy.API/GetCities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetCities(ctx, req.(*RequestCityAndShop))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCityAndShop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_pharmacy.API/GetShops",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetShops(ctx, req.(*RequestCityAndShop))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_pharmacy.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoodsOnCompetitorSku",
			Handler:    _API_GetGoodsOnCompetitorSku_Handler,
		},
		{
			MethodName: "GetAllProducts",
			Handler:    _API_GetAllProducts_Handler,
		},
		{
			MethodName: "GetGoodsOnOneCodePuls",
			Handler:    _API_GetGoodsOnOneCodePuls_Handler,
		},
		{
			MethodName: "GetCities",
			Handler:    _API_GetCities_Handler,
		},
		{
			MethodName: "GetShops",
			Handler:    _API_GetShops_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
